# Generated by Django 5.2.3 on 2025-06-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barrios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "barrios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Caracteristicas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("tipo", models.CharField(blank=True, max_length=8, null=True)),
                ("unidad", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "caracteristicas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ciudades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ciudades",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ejecuciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=255)),
                ("total_inmuebles", models.IntegerField(blank=True, null=True)),
                ("inmuebles_nuevos", models.IntegerField(blank=True, null=True)),
                ("inmuebles_actualizados", models.IntegerField(blank=True, null=True)),
                ("inmuebles_sin_cambios", models.IntegerField(blank=True, null=True)),
                ("imagenes_descargadas", models.IntegerField(blank=True, null=True)),
                ("errores", models.IntegerField(blank=True, null=True)),
                ("tiempo_ejecucion", models.IntegerField(blank=True, null=True)),
                ("fecha_inicio", models.DateTimeField(blank=True, null=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ejecuciones",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EstadosInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "estados_inmueble",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Etiquetas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        db_comment="Nombre de la etiqueta", max_length=255, unique=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        db_comment="Color en formato hexadecimal",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, db_comment="Descripción de la etiqueta", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "etiquetas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="HistorialCambios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campo", models.CharField(max_length=255)),
                ("valor_anterior", models.TextField(blank=True, null=True)),
                ("valor_nuevo", models.TextField(blank=True, null=True)),
                ("fecha_cambio", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "historial_cambios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Imagenes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255)),
                ("url_local", models.CharField(blank=True, max_length=255, null=True)),
                ("orden", models.IntegerField(blank=True, null=True)),
                ("descargada", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "imagenes",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InmuebleCaracteristicas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valor_texto",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "valor_numerico",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("valor_booleano", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "db_table": "inmueble_caracteristicas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Inmuebles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ref", models.IntegerField(unique=True)),
                (
                    "codigo_sincronizacion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("titulo", models.CharField(blank=True, max_length=255, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("descripcion_corta", models.TextField(blank=True, null=True)),
                (
                    "ciudad_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "barrio_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_inmueble_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uso_inmueble_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "estado_inmueble_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "tipo_consignacion_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "asesor_nombre",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "area_construida",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "area_privada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "area_terreno",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("habitaciones", models.IntegerField(blank=True, null=True)),
                ("banos", models.IntegerField(blank=True, null=True)),
                ("garajes", models.IntegerField(blank=True, null=True)),
                ("estrato", models.IntegerField(blank=True, null=True)),
                (
                    "precio_venta",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "precio_canon",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "precio_administracion",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                ("latitud", models.CharField(blank=True, max_length=255, null=True)),
                ("longitud", models.CharField(blank=True, max_length=255, null=True)),
                ("activo", models.IntegerField(blank=True, null=True)),
                ("destacado", models.IntegerField(blank=True, null=True)),
                ("en_caliente", models.IntegerField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_sincronizacion", models.DateTimeField(blank=True, null=True)),
                ("hash_datos", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        db_comment="URL amigable para el inmueble",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "inmuebles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InmueblesEstados",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inmueble_ref",
                    models.IntegerField(
                        db_comment="Referencia del inmueble (campo ref de la tabla inmuebles)"
                    ),
                ),
                (
                    "codigo_sincronizacion",
                    models.CharField(
                        db_comment="Código de sincronización del inmueble",
                        max_length=255,
                    ),
                ),
                (
                    "activo",
                    models.IntegerField(
                        blank=True,
                        db_comment="Estado del campo activo que debe mantenerse entre sincronizaciones",
                        null=True,
                    ),
                ),
                (
                    "destacado",
                    models.IntegerField(
                        blank=True,
                        db_comment="Estado del campo destacado que debe mantenerse entre sincronizaciones",
                        null=True,
                    ),
                ),
                (
                    "en_caliente",
                    models.IntegerField(
                        blank=True,
                        db_comment="Estado del campo en_caliente que debe mantenerse entre sincronizaciones",
                        null=True,
                    ),
                ),
                ("fecha_modificacion", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "inmuebles_estados",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="InmueblesEtiquetas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "inmuebles_etiquetas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TipoConsignacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipo_consignacion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TiposInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "tipos_inmueble",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UsosInmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "usos_inmueble",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Assesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("telefono", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        help_text="Selecciona una imagen para el asesor",
                        null=True,
                        upload_to="asesores/",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        db_comment="Indica si el asesor está activo o no", default=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Asesor",
                "verbose_name_plural": "Asesores",
                "db_table": "asesores",
            },
        ),
    ]
