# Generated by Django 5.2.3 on 2025-06-13 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inmobiliaria", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "ciudades",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Ciudades",
        ),
        migrations.DeleteModel(
            name="Ejecuciones",
        ),
        migrations.DeleteModel(
            name="HistorialCambios",
        ),
    ]
