# Generated by Django 5.2.3 on 2025-06-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inmobiliaria", "0002_city_delete_ciudades_delete_ejecuciones_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Caracteristica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("tipo", models.CharField(blank=True, max_length=8, null=True)),
                (
                    "unidad",
                    models.CharField(
                        blank=True,
                        choices=[("texto", "Texto"), ("numerico", "Numérico")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Característica",
                "verbose_name_plural": "Características",
                "db_table": "caracteristicas",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="Caracteristicas",
        ),
        migrations.AlterModelOptions(
            name="city",
            options={
                "managed": False,
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
            },
        ),
        migrations.AlterModelOptions(
            name="etiquetas",
            options={
                "managed": False,
                "verbose_name": "Etiqueta",
                "verbose_name_plural": "Etiquetas",
            },
        ),
        migrations.AlterModelOptions(
            name="imagenes",
            options={
                "managed": True,
                "ordering": ["orden", "created_at"],
                "verbose_name": "Imagen del Inmueble",
                "verbose_name_plural": "Imágenes del Inmueble",
            },
        ),
        migrations.AlterModelOptions(
            name="inmueblecaracteristicas",
            options={
                "managed": True,
                "verbose_name": "Característica del Inmueble",
                "verbose_name_plural": "Características del Inmueble",
            },
        ),
        migrations.AlterModelOptions(
            name="inmuebles",
            options={
                "managed": False,
                "verbose_name": "Inmueble",
                "verbose_name_plural": "Inmuebles",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoconsignacion",
            options={
                "managed": False,
                "verbose_name": "Tipo de Consignación",
                "verbose_name_plural": "Tipos de Consignación",
            },
        ),
        migrations.AlterModelOptions(
            name="tiposinmueble",
            options={
                "managed": False,
                "verbose_name": "Tipo de Inmueble",
                "verbose_name_plural": "Tipos de Inmuebles",
            },
        ),
        migrations.AlterModelOptions(
            name="usosinmueble",
            options={
                "managed": False,
                "verbose_name": "Uso de Inmueble",
                "verbose_name_plural": "Usos de Inmuebles",
            },
        ),
    ]
